module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#2D6A4F',
        'on-primary': '#ffffff',
        'primary-container': '#b1f0ce',
        'on-primary-container': '#002114',
        secondary: '#7d5800',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffb702',
        'on-secondary-container': '#6b4b00',
        tertiary: '#713638',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbfbe2',
        'on-background': '#1b1d0e',
        surface: '#fbfbe2',
        'on-surface': '#1b1d0e',
        'surface-variant': '#e4e4cc',
        'on-surface-variant': '#5d655f',
        outline: '#707973',
        'surface-container-low': '#f5f5dc',
        'surface-container': '#efefd7',
        'surface-container-high': '#eaead1',
      },
      fontFamily: {
        headline: ['Nothing English Headline', 'Namekoz032 Light Web', 'Padauk', 'sans-serif'],
        body: ['Nothing English Text', 'Namekoz032 Light Web', 'Padauk', 'Noto Serif', 'serif'],
        label: ['Nothing English Text', 'Namekoz032 Light Web', 'Padauk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
