import { useEffect, useMemo, useState } from 'react'

const API_BASE = 'http://127.0.0.1:8000'

const badgeClass = (risk) => {
  if (risk.includes('Flood')) return 'bg-red-100 text-red-700 border-red-200'
  if (risk.includes('Drought')) return 'bg-orange-100 text-orange-700 border-orange-200'
  if (risk.includes('Storm')) return 'bg-amber-100 text-amber-700 border-amber-200'
  return 'bg-blue-100 text-blue-700 border-blue-200'
}

const defaultForm = {
  location: 'Hlegu',
  crop: 'Rice',
  rainfall_mm_next_3_days: 160,
  temperature_c: 31,
  soil_moisture_pct: 80,
  wind_kph: 18,
}

export default function App() {
  const [alerts, setAlerts] = useState([])
  const [selectedAlert, setSelectedAlert] = useState(null)
  const [form, setForm] = useState(defaultForm)
  const [generatedAlert, setGeneratedAlert] = useState(null)
  const [status, setStatus] = useState('Loading sample alerts...')

  useEffect(() => {
    fetch(`${API_BASE}/sample-alerts`)
      .then((res) => res.json())
      .then((data) => {
        setAlerts(data.alerts || [])
        setSelectedAlert((data.alerts || [])[0] || null)
        setStatus('Connected to prediction API')
      })
      .catch(() => {
        setStatus('Could not connect to backend. Start FastAPI on port 8000.')
      })
  }, [])

  const currentAlert = useMemo(() => generatedAlert || selectedAlert, [generatedAlert, selectedAlert])

  const updateField = (key, value) => {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  const runPrediction = async (e) => {
    e.preventDefault()
    setStatus('Generating prediction...')
    try {
      const response = await fetch(`${API_BASE}/predict`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...form,
          rainfall_mm_next_3_days: Number(form.rainfall_mm_next_3_days),
          temperature_c: Number(form.temperature_c),
          soil_moisture_pct: Number(form.soil_moisture_pct),
          wind_kph: Number(form.wind_kph),
        }),
      })
      const data = await response.json()
      setGeneratedAlert(data)
      setStatus('Prediction ready')
    } catch {
      setStatus('Prediction failed. Check that backend is running.')
    }
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 p-6 md:p-10">
      <div className="max-w-7xl mx-auto space-y-8">
        <header className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
            <div>
              <p className="text-sm font-semibold tracking-wide uppercase text-emerald-700">Hackathon MVP</p>
              <h1 className="text-4xl md:text-5xl font-bold mt-2">Climate Risk Prediction System</h1>
              <p className="mt-4 text-slate-600 max-w-3xl">
                A working prototype that combines a simple prediction API with a farmer-friendly dashboard and SMS-ready alert output.
              </p>
            </div>
            <div className="bg-slate-100 rounded-2xl px-4 py-3 text-sm border border-slate-200">
              <span className="font-semibold">System status:</span> {status}
            </div>
          </div>
        </header>

        <section className="grid xl:grid-cols-3 gap-6">
          <div className="xl:col-span-2 space-y-6">
            <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-6">
              <div className="flex items-center justify-between mb-5 gap-4">
                <div>
                  <h2 className="text-2xl font-semibold">Sample Alerts</h2>
                  <p className="text-slate-600 mt-1">These are generated by the backend from simple weather inputs.</p>
                </div>
              </div>
              <div className="space-y-4">
                {alerts.map((alert, index) => (
                  <button
                    key={`${alert.location}-${index}`}
                    onClick={() => {
                      setSelectedAlert(alert)
                      setGeneratedAlert(null)
                    }}
                    className="w-full text-left rounded-2xl border border-slate-200 p-5 bg-slate-50 hover:bg-slate-100 transition"
                  >
                    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
                      <div>
                        <div className="text-lg font-semibold">{alert.location} • {alert.crop}</div>
                        <div className="text-sm text-slate-500 mt-1">Prediction window: {alert.timing}</div>
                      </div>
                      <span className={`inline-flex items-center rounded-full border px-3 py-1 text-sm font-medium ${badgeClass(alert.risk)}`}>
                        {alert.risk}
                      </span>
                    </div>
                    <p className="mt-3 text-slate-700">{alert.advice}</p>
                  </button>
                ))}
              </div>
            </div>

            <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-6">
              <h2 className="text-2xl font-semibold">Run New Prediction</h2>
              <p className="text-slate-600 mt-1">Change the climate inputs below and generate a fresh recommendation.</p>
              <form className="mt-5 grid md:grid-cols-2 gap-4" onSubmit={runPrediction}>
                {[
                  ['location', 'Location', 'text'],
                  ['crop', 'Crop', 'text'],
                  ['rainfall_mm_next_3_days', 'Rainfall next 3 days (mm)', 'number'],
                  ['temperature_c', 'Temperature (°C)', 'number'],
                  ['soil_moisture_pct', 'Soil moisture (%)', 'number'],
                  ['wind_kph', 'Wind (kph)', 'number'],
                ].map(([key, label, type]) => (
                  <label key={key} className="block">
                    <span className="text-sm font-medium text-slate-700">{label}</span>
                    <input
                      type={type}
                      value={form[key]}
                      onChange={(e) => updateField(key, e.target.value)}
                      className="mt-1 w-full rounded-2xl border border-slate-300 px-4 py-3 bg-slate-50 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                  </label>
                ))}
                <div className="md:col-span-2">
                  <button className="rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white px-5 py-3 font-semibold shadow-sm">
                    Generate Prediction
                  </button>
                </div>
              </form>
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-6">
              <h2 className="text-2xl font-semibold">Selected Alert</h2>
              {currentAlert ? (
                <div className="mt-4 space-y-4">
                  <div>
                    <div className="text-lg font-semibold">{currentAlert.location} • {currentAlert.crop}</div>
                    <div className="text-sm text-slate-500 mt-1">Forecast window: {currentAlert.timing}</div>
                  </div>
                  <span className={`inline-flex items-center rounded-full border px-3 py-1 text-sm font-medium ${badgeClass(currentAlert.risk)}`}>
                    {currentAlert.risk}
                  </span>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200">
                      <div className="text-sm text-slate-500">Confidence</div>
                      <div className="text-3xl font-bold mt-1">{currentAlert.confidence}%</div>
                    </div>
                    <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200">
                      <div className="text-sm text-slate-500">Delivery</div>
                      <div className="text-2xl font-bold mt-1">App + SMS</div>
                    </div>
                  </div>
                  <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200">
                    <div className="text-sm text-slate-500">Advice</div>
                    <div className="mt-1 font-medium">{currentAlert.advice}</div>
                  </div>
                </div>
              ) : (
                <p className="mt-4 text-slate-600">No alert selected yet.</p>
              )}
            </div>

            <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-6">
              <h2 className="text-2xl font-semibold">SMS Preview</h2>
              <div className="mt-4 rounded-3xl bg-slate-900 text-white p-5 shadow-inner min-h-40">
                <div className="text-xs uppercase tracking-wide text-slate-400">Farmer Alert</div>
                <p className="mt-3 text-sm leading-6">{currentAlert ? currentAlert.sms : 'Generate or select an alert to see the SMS version.'}</p>
              </div>
            </div>

            <div className="bg-gradient-to-br from-emerald-600 to-emerald-700 rounded-3xl shadow-sm p-6 text-white">
              <h2 className="text-2xl font-semibold">How It Works</h2>
              <ol className="mt-4 space-y-2 text-emerald-50 list-decimal list-inside">
                <li>Input weather and farm conditions</li>
                <li>Backend calculates climate risk</li>
                <li>System converts risk into plain-language advice</li>
                <li>Alert is shown in-app and as an SMS fallback</li>
              </ol>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}
